# Generated by Django 5.1.6 on 2025-02-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_perticipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='perticipants',
            new_name='participants',
        ),
    ]
